# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    build:
      runs-on: ubuntu-latest
      strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}
            architecture: x64
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Install linter
          run: pip install pylint
        - name: Lint files
          run: find . -name '*.py' -exec pylint {} \;
        - name: Run tests
          run: python -m unittest
